/**
 * Application-level TypeScript types for CruxMD frontend.
 *
 * API types are auto-generated by @hey-api/openapi-ts in lib/generated/.
 * This file contains only app-specific types that extend the generated ones.
 */

// Re-export generated types for convenience
export type { BundleLoadResponse } from "./generated";
